port: 8001
socks-port: 1081
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
# log-level: warning # Fix ClashX Pro Config Error by commented!

proxies:
  - name: 'Free-SSR'
    type: ssr
    server: ssrfree3.free4444.xyz
    port: 44000
    cipher: none
    password: dongtaiwang.com
    obfs: tls1.2_ticket_auth
    protocol: auth_chain_a

  - name: 'Free-SS'
    type: ss
    server: 185.216.72.16
    port: 15567
    cipher: aes-256-gcm
    password: dongtaiwang.com
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket
      host: cloudfront.com
      path: /MCvTP
      mux: 8

proxy-groups:
  - name: '代理节点'
    type: select
    proxies:
      - Trojan-Go-USALos
      - Free-SSR
      - Free-SS

rules:
  # 广告
  - DOMAIN-SUFFIX,ad.com,REJECT

  # 禁止代理
  # - DOMAIN-KEYWORD,kdocs,DIRECT

  # GeoIP China
  - GEOIP,CN,DIRECT

  # 代理 Keyword
  - DOMAIN-KEYWORD,google,代理节点
  - DOMAIN-KEYWORD,blogspot,代理节点
  - DOMAIN-KEYWORD,github,代理节点

  # 代理 Suffix
  # - DOMAIN-SUFFIX,apple.co,代理节点
  # - DOMAIN-SUFFIX,cdn-apple.com,代理节点
  # - DOMAIN-SUFFIX,apple.com,代理节点
  - DOMAIN-SUFFIX,macyy.cn,代理节点
  - DOMAIN-SUFFIX,proxyman.io,代理节点
  - DOMAIN-SUFFIX,gravatar.com,代理节点
  - DOMAIN-SUFFIX,bitwarden.com,代理节点
  - DOMAIN-SUFFIX,boxjs.app,代理节点
  - DOMAIN-SUFFIX,machbbs.com,代理节点
  - DOMAIN-SUFFIX,paypal.com,代理节点
  - DOMAIN-SUFFIX,arc.net,代理节点
  - DOMAIN-SUFFIX,launchdarkly.com,代理节点
  - DOMAIN-SUFFIX,vivaldi.com,代理节点
  - DOMAIN-SUFFIX,discord.gg,代理节点
  - DOMAIN-SUFFIX,discordapp.com,代理节点
  - DOMAIN-SUFFIX,discord.com,代理节点
  - DOMAIN-SUFFIX,solidjs.com,代理节点
  - DOMAIN-SUFFIX,bandwagonhost.com,代理节点
  - DOMAIN-SUFFIX,trafficmanager.net,代理节点
  - DOMAIN-SUFFIX,549.tv,代理节点
  - DOMAIN-SUFFIX,v2ex.com,代理节点
  - DOMAIN-SUFFIX,vercel.app,代理节点
  - DOMAIN-SUFFIX,obsproject.com,代理节点
  - DOMAIN-SUFFIX,js.org,代理节点
  - DOMAIN-SUFFIX,tunnelblick.net,代理节点
  - DOMAIN-SUFFIX,rollupjs.org,代理节点
  - DOMAIN-SUFFIX,appspot.com,代理节点
  - DOMAIN-SUFFIX,myunidays.uk,代理节点
  - DOMAIN-SUFFIX,getoutline.org,代理节点
  - DOMAIN-SUFFIX,gvt0.com,代理节点
  - DOMAIN-SUFFIX,gvt1.com,代理节点
  - DOMAIN-SUFFIX,gvt3.com,代理节点
  - DOMAIN-SUFFIX,xn--ngstr-lra8j.com,代理节点
  - DOMAIN-SUFFIX,jenkins.io,代理节点
  - DOMAIN-SUFFIX,jim-nielsen.com,代理节点
  - DOMAIN-SUFFIX,neovim.io,代理节点
  - DOMAIN-SUFFIX,figma.com,代理节点
  - DOMAIN-SUFFIX,soliditylang.org,代理节点
  - DOMAIN-SUFFIX,who.int,代理节点
  - DOMAIN-SUFFIX,the-algorithms.com,代理节点
  - DOMAIN-SUFFIX,diygod.me,代理节点
  - DOMAIN-SUFFIX,githack.com,代理节点
  - DOMAIN-SUFFIX,jetbrains.com,代理节点
  - DOMAIN-SUFFIX,djr.com,代理节点
  - DOMAIN-SUFFIX,workona.com,代理节点
  - DOMAIN-SUFFIX,typingclub.com,代理节点
  - DOMAIN-SUFFIX,vsassets.io,代理节点
  - DOMAIN-SUFFIX,lncn.org,代理节点
  - DOMAIN-SUFFIX,browserl.ist,代理节点
  - DOMAIN-SUFFIX,babeljs.io,代理节点
  - DOMAIN-SUFFIX,jestjs.io,代理节点
  - DOMAIN-SUFFIX,gitmoji.dev,代理节点
  - DOMAIN-SUFFIX,azureedge.net,代理节点
  - DOMAIN-SUFFIX,typescriptlang.org,代理节点
  - DOMAIN-SUFFIX,gitpod.io,代理节点
  - DOMAIN-SUFFIX,npmtrends.com,代理节点
  - DOMAIN-SUFFIX,visualstudio.com,代理节点
  - DOMAIN-SUFFIX,adobe.com,代理节点
  - DOMAIN-SUFFIX,ieonchrome.com,代理节点
  - DOMAIN-SUFFIX,ietab.net,代理节点
  - DOMAIN-SUFFIX,github.surf,代理节点
  - DOMAIN-SUFFIX,github1s.com,代理节点
  - DOMAIN-SUFFIX,greensock.com,代理节点
  - DOMAIN-SUFFIX,csstriggers.com,代理节点
  - DOMAIN-SUFFIX,bpmn.io,代理节点
  - DOMAIN-SUFFIX,vueschool.io,代理节点
  - DOMAIN-SUFFIX,unpkg.com,代理节点
  - DOMAIN-SUFFIX,getfiddler.com,代理节点
  - DOMAIN-SUFFIX,telerik.com,代理节点
  - DOMAIN-SUFFIX,microsoft.com,代理节点
  - DOMAIN-SUFFIX,vuemastery.com,代理节点
  - DOMAIN-SUFFIX,fontsarena.com,代理节点
  - DOMAIN-SUFFIX,prettier.io,代理节点
  - DOMAIN-SUFFIX,necta.us,代理节点
  - DOMAIN-SUFFIX,pstmn.io,代理节点
  - DOMAIN-SUFFIX,hp.com,代理节点
  - DOMAIN-SUFFIX,axshare.com,代理节点
  - DOMAIN-SUFFIX,vuejs.org,代理节点
  - DOMAIN-SUFFIX,pqrs.org,代理节点
  - DOMAIN-SUFFIX,samba.tv,代理节点
  - DOMAIN-SUFFIX,starz.com,代理节点
  - DOMAIN-SUFFIX,tunefind.com,代理节点
  - DOMAIN-SUFFIX,stackblitz.com,代理节点
  - DOMAIN-SUFFIX,codesandbox.io,代理节点
  - DOMAIN-SUFFIX,filext.com,代理节点
  - DOMAIN-SUFFIX,codepen.io,代理节点
  - DOMAIN-SUFFIX,yarnpkg.com,代理节点
  - DOMAIN-SUFFIX,pilotmoon.com,代理节点
  - DOMAIN-SUFFIX,statuspage.io,代理节点
  - DOMAIN-SUFFIX,hubapi.com,代理节点
  - DOMAIN-SUFFIX,stripe.com,代理节点
  - DOMAIN-SUFFIX,travis-ci.org,代理节点
  - DOMAIN-SUFFIX,travis-ci.com,代理节点
  - DOMAIN-SUFFIX,dartlang.org,代理节点
  - DOMAIN-SUFFIX,goodev.org,代理节点
  - DOMAIN-SUFFIX,npmjs.com,代理节点
  - DOMAIN-SUFFIX,digitalocean.com,代理节点
  - DOMAIN-SUFFIX,gitlab.com,代理节点
  - DOMAIN-SUFFIX,reddit.com,代理节点
  - DOMAIN-SUFFIX,vugu.org,代理节点
  - DOMAIN-SUFFIX,meditech.com,代理节点
  - DOMAIN-SUFFIX,jsfiddle.net,代理节点
  - DOMAIN-SUFFIX,steemit.com,代理节点
  - DOMAIN-SUFFIX,233v2.com,代理节点
  - DOMAIN-SUFFIX,cloud.google,代理节点
  - DOMAIN-SUFFIX,soundcloud.com,代理节点
  - DOMAIN-SUFFIX,sndcdn.com,代理节点
  - DOMAIN-SUFFIX,appboycdn,代理节点
  - DOMAIN-SUFFIX,whosampled.com,代理节点
  # - DOMAIN-SUFFIX,apple.com,代理节点
  - DOMAIN-SUFFIX,quora.com,代理节点
  - DOMAIN-SUFFIX,stackoverflow.com,代理节点
  - DOMAIN-SUFFIX,spotify.com,代理节点
  - DOMAIN-SUFFIX,sentry.io,代理节点
  - DOMAIN-SUFFIX,fastly-insights.com,代理节点
  - DOMAIN-SUFFIX,scdn.co,代理节点
  - DOMAIN-SUFFIX,akamaized.net,代理节点
  - DOMAIN-SUFFIX,futurehosting.com,代理节点
  - DOMAIN-SUFFIX,superuser.com,代理节点
  - DOMAIN-SUFFIX,nordtheme.com,代理节点
  - DOMAIN-SUFFIX,vimawesome.com,代理节点
  - DOMAIN-SUFFIX,nerdfonts.com,代理节点
  - DOMAIN-SUFFIX,docs.rs,代理节点
  - DOMAIN-SUFFIX,imdb.com,代理节点
  - DOMAIN-SUFFIX,postman.co,代理节点
  - DOMAIN-SUFFIX,postman.com,代理节点
  - DOMAIN-SUFFIX,single-spa.js.org,代理节点
  - DOMAIN-SUFFIX,jsdelivr.com,代理节点
  - DOMAIN-SUFFIX,freenom.com,代理节点
  - DOMAIN-SUFFIX,docker.com,代理节点
  - DOMAIN-SUFFIX,fontawesome.com,代理节点
  - DOMAIN-SUFFIX,optimizely.com,代理节点
  - DOMAIN-SUFFIX,truste.com,代理节点
  - DOMAIN-SUFFIX,mouseflow.com,代理节点
  - DOMAIN-SUFFIX,licdn.com,代理节点
  - DOMAIN-SUFFIX,ads-twitter.com,代理节点
  - DOMAIN-SUFFIX,marketo.net,代理节点
  - DOMAIN-SUFFIX,engagio.com,代理节点
  - DOMAIN-SUFFIX,bizible.com,代理节点
  - DOMAIN-SUFFIX,segment.io,代理节点
  - DOMAIN-SUFFIX,doubleclick.net,代理节点
  - DOMAIN-SUFFIX,mktoresp.com,代理节点
  - DOMAIN-SUFFIX,adsymptotic.com,代理节点
  - DOMAIN-SUFFIX,linkedin.com,代理节点
  - DOMAIN-SUFFIX,gravatar.com,代理节点
  - DOMAIN-SUFFIX,hubspot.com,代理节点
  - DOMAIN-SUFFIX,hs-analytics.net,代理节点
  - DOMAIN-SUFFIX,wikipedia.com,代理节点
  - DOMAIN-SUFFIX,logitech.com,代理节点
  - DOMAIN-SUFFIX,logi.com,代理节点
  - DOMAIN-SUFFIX,sstatic.net,代理节点
  - DOMAIN-SUFFIX,quantserve.com,代理节点
  - DOMAIN-SUFFIX,scorecardresearch.com,代理节点
  - DOMAIN-SUFFIX,elastic.co,代理节点
  - DOMAIN-SUFFIX,electronjs.org,代理节点
  - DOMAIN-SUFFIX,electron.build,代理节点
  - DOMAIN-SUFFIX,antv.vision,代理节点
  - DOMAIN-SUFFIX,speedtest.net,代理节点
  - DOMAIN-SUFFIX,pinterest.com,代理节点
  - DOMAIN-SUFFIX,hs-scripts.com,代理节点
  - DOMAIN-SUFFIX,hs-banner.com,代理节点
  - DOMAIN-SUFFIX,rime.im,代理节点
  - DOMAIN-SUFFIX,nog.net,代理节点
  - DOMAIN-SUFFIX,meiyuan.in,代理节点
  - DOMAIN-SUFFIX,paperapp.net,代理节点
  - DOMAIN-SUFFIX,unsplash.com,代理节点
  - DOMAIN-SUFFIX,mysql.com,代理节点
  - DOMAIN-SUFFIX,fontbureau.com,代理节点
  - DOMAIN-SUFFIX,github.com,代理节点
  - DOMAIN-SUFFIX,githubusercontent.com,代理节点
  - DOMAIN-SUFFIX,githubassets.com,代理节点
  - DOMAIN-SUFFIX,githubapp.com,代理节点
  - DOMAIN-SUFFIX,github.io,代理节点
  - DOMAIN-SUFFIX,vpngate.net,代理节点
  - DOMAIN-SUFFIX,greatfire.org,代理节点
  - DOMAIN-SUFFIX,tox.im,代理节点
  - DOMAIN-SUFFIX,proxifier.com,代理节点
  - DOMAIN-SUFFIX,dnscrypt.org,代理节点
  - DOMAIN-SUFFIX,atgfw.org,代理节点
  - DOMAIN-SUFFIX,chinagfw.org,代理节点
  - DOMAIN-SUFFIX,whatismyip.com,代理节点
  - DOMAIN-SUFFIX,goagentplus.com,代理节点
  - DOMAIN-SUFFIX,shadowsocks.org,代理节点
  - DOMAIN-SUFFIX,falcop.com,代理节点
  - DOMAIN-SUFFIX,getlantern.org,代理节点
  - DOMAIN-SUFFIX,furbo.org,代理节点
  - DOMAIN-SUFFIX,goagentx.com,代理节点
  - DOMAIN-SUFFIX,sourceforge.net,代理节点
  - DOMAIN-SUFFIX,torproject.org,代理节点
  - DOMAIN-SUFFIX,hideme.io,代理节点
  - DOMAIN-SUFFIX,mozilla.org,代理节点
  - DOMAIN-SUFFIX,shadowx.work,代理节点
  - DOMAIN-SUFFIX,v2ray.com,代理节点
  - DOMAIN-SUFFIX,astrill.com,代理节点
  - DOMAIN-SUFFIX,deviantart.com,代理节点
  - DOMAIN-SUFFIX,disqus.com,代理节点
  - DOMAIN-SUFFIX,disquscdn.com,代理节点
  - DOMAIN-SUFFIX,tumblr.com,代理节点
  - DOMAIN-SUFFIX,flickr.com,代理节点
  - DOMAIN-SUFFIX,imgur.com,代理节点
  - DOMAIN-SUFFIX,evozi.com,代理节点
  - DOMAIN-SUFFIX,live.com,代理节点
  - DOMAIN-SUFFIX,1drv.com,代理节点
  - DOMAIN-SUFFIX,evernote.com,代理节点
  - DOMAIN-SUFFIX,wp.com,代理节点
  - DOMAIN-SUFFIX,yam.com,代理节点
  - DOMAIN-SUFFIX,ashchan.com,代理节点
  - DOMAIN-SUFFIX,zuckclub.com,代理节点
  - DOMAIN-SUFFIX,blogspot.com,代理节点
  - DOMAIN-SUFFIX,blogspot.jp,代理节点
  - DOMAIN-SUFFIX,zalex2014.tk,代理节点
  - DOMAIN-SUFFIX,coreygilmore.com,代理节点
  - DOMAIN-SUFFIX,wordpress.com,代理节点
  - DOMAIN-SUFFIX,blogimg.jp,代理节点
  - DOMAIN-SUFFIX,leaskh.com,代理节点
  - DOMAIN-SUFFIX,blogger.com,代理节点
  - DOMAIN-SUFFIX,hexo.io,代理节点
  - DOMAIN-SUFFIX,medium.com,代理节点
  - DOMAIN-SUFFIX,rfi.my,代理节点
  - DOMAIN-SUFFIX,rfi.fr,代理节点
  - DOMAIN-SUFFIX,washingtonpost.com,代理节点
  - DOMAIN-SUFFIX,tmagazine.com,代理节点
  - DOMAIN-SUFFIX,nytimes.com,代理节点
  - DOMAIN-SUFFIX,nytimg.com,代理节点
  - DOMAIN-SUFFIX,imrworldwide.com,代理节点
  - DOMAIN-SUFFIX,rankingsandreviews.com,代理节点
  - DOMAIN-SUFFIX,usnews.com,代理节点
  - DOMAIN-SUFFIX,bbc.co.uk,代理节点
  - DOMAIN-SUFFIX,bbci.co.uk,代理节点
  - DOMAIN-SUFFIX,bbc.com,代理节点
  - DOMAIN-SUFFIX,on-match.com,代理节点
  - DOMAIN-SUFFIX,solidot.org,代理节点
  - DOMAIN-SUFFIX,engadget.com,代理节点
  - DOMAIN-SUFFIX,amazonaws.com,代理节点
  - DOMAIN-SUFFIX,fastly.net,代理节点
  - DOMAIN-SUFFIX,akamaihd.net,代理节点
  - DOMAIN-SUFFIX,blogsmithmedia.com,代理节点
  - DOMAIN-SUFFIX,bit.ly,代理节点
  - DOMAIN-SUFFIX,d.pr,代理节点
  - DOMAIN-SUFFIX,ow.ly,代理节点
  - DOMAIN-SUFFIX,ift.tt,代理节点
  - DOMAIN-SUFFIX,nateparrott.com,代理节点
  - DOMAIN-SUFFIX,stacksocial.com,代理节点
  - DOMAIN-SUFFIX,feedly.com,代理节点
  - DOMAIN-SUFFIX,acgtea.com,代理节点
  - DOMAIN-SUFFIX,ieee.org,代理节点
  - DOMAIN-SUFFIX,mathoverflow.net,代理节点
  - DOMAIN-SUFFIX,stackexchange.com,代理节点
  - DOMAIN-SUFFIX,academia.edu,代理节点
  - DOMAIN-SUFFIX,geogebra.org,代理节点
  - DOMAIN-SUFFIX,golang.org,代理节点
  - DOMAIN-SUFFIX,netspeak.org,代理节点
  - DOMAIN-SUFFIX,endreslab.com,代理节点
  - DOMAIN-SUFFIX,illinois.edu,代理节点
  - DOMAIN-SUFFIX,berkeley.edu,代理节点
  - DOMAIN-SUFFIX,wisc.edu,代理节点
  - DOMAIN-SUFFIX,cmu.edu,代理节点
  - DOMAIN-SUFFIX,rochester.edu,代理节点
  - DOMAIN-SUFFIX,purdue.edu,代理节点
  - DOMAIN-SUFFIX,technolutions.net,代理节点
  - DOMAIN-SUFFIX,netflix.com,代理节点
  - DOMAIN-SUFFIX,ldoceonline.com,代理节点
  - DOMAIN-SUFFIX,freedicts.com,代理节点
  - DOMAIN-SUFFIX,formacx.com,代理节点
  - DOMAIN-SUFFIX,trionworlds.com,代理节点
  - DOMAIN-SUFFIX,line.me,代理节点
  - DOMAIN-SUFFIX,e-hentai.org,代理节点
  - DOMAIN-SUFFIX,nhentai.net,代理节点
  - DOMAIN-SUFFIX,nicovideo.jp,代理节点
  - DOMAIN-SUFFIX,nimg.jp,代理节点
  - DOMAIN-SUFFIX,pixnet.net,代理节点
  - DOMAIN-SUFFIX,fc2.com,代理节点
  - DOMAIN-SUFFIX,nyaatorrents.org,代理节点
  - DOMAIN-SUFFIX,nyaa.se,代理节点
  - DOMAIN-SUFFIX,share.dmhy.org,代理节点
  - DOMAIN-SUFFIX,loli.us,代理节点
  - DOMAIN-SUFFIX,facebook.net,代理节点
  - DOMAIN-SUFFIX,instagram.com,代理节点
  - DOMAIN-SUFFIX,facebook.com,代理节点
  - DOMAIN-SUFFIX,fb.me,代理节点
  - DOMAIN-SUFFIX,cdninstagram.com,代理节点
  - DOMAIN-SUFFIX,fbcdn.net,代理节点
  - DOMAIN-SUFFIX,booth.pm,代理节点
  - DOMAIN-SUFFIX,telegram.org,代理节点
  - DOMAIN-SUFFIX,telegram.me,代理节点
  - DOMAIN-SUFFIX,wikipedia.org,代理节点
  - DOMAIN-SUFFIX,pixiv.net,代理节点
  - DOMAIN-SUFFIX,twitch.tv,代理节点
  - DOMAIN-SUFFIX,twitter.com,代理节点
  - DOMAIN-SUFFIX,t.co,代理节点
  - DOMAIN-SUFFIX,twimg.com,代理节点
  - DOMAIN-SUFFIX,gmail.com,代理节点
  - DOMAIN-SUFFIX,googlemail.com,代理节点
  - DOMAIN-SUFFIX,mailchimp.com,代理节点
  - DOMAIN-SUFFIX,mail-archive.com,代理节点
  - DOMAIN-SUFFIX,google.com,代理节点
  - DOMAIN-SUFFIX,goo.gl,代理节点
  - DOMAIN-SUFFIX,google.com.hk,代理节点
  - DOMAIN-SUFFIX,google.com.tw,代理节点
  - DOMAIN-SUFFIX,google.co.jp,代理节点
  - DOMAIN-SUFFIX,googlecode.com,代理节点
  - DOMAIN-SUFFIX,googleapis.com,代理节点
  - DOMAIN-SUFFIX,ggpht.com,代理节点
  - DOMAIN-SUFFIX,youtube.com,代理节点
  - DOMAIN-SUFFIX,youtu.be,代理节点
  - DOMAIN-SUFFIX,ytimg.com,代理节点
  - DOMAIN-SUFFIX,youtube-nocookie.com,代理节点
  - DOMAIN-SUFFIX,googlevideo.com,代理节点
  - DOMAIN-SUFFIX,sketchup.com,代理节点
  - DOMAIN-SUFFIX,gstatic.com,代理节点
  - DOMAIN-SUFFIX,google-analytics.com,代理节点
  - DOMAIN-SUFFIX,googleusercontent.com,代理节点
  - DOMAIN-SUFFIX,chrome.com,代理节点
  - DOMAIN-SUFFIX,g.co,代理节点
  - DOMAIN-SUFFIX,googledrive.com,代理节点
  - DOMAIN-SUFFIX,googletagmanager.com,代理节点
  - DOMAIN-SUFFIX,googleadservices.com,代理节点
  - DOMAIN-SUFFIX,abc.xyz,代理节点
  - DOMAIN-SUFFIX,dropbox.com,代理节点
  - DOMAIN-SUFFIX,dropboxusercontent.com,代理节点
  - DOMAIN-SUFFIX,dropboxwiki.com,代理节点
  - DOMAIN-SUFFIX,mzstatic.com,代理节点
  - DOMAIN-SUFFIX,cloudfront.net,代理节点
  - DOMAIN-SUFFIX,colwiz.com,代理节点

  - MATCH,DIRECT
